### ISSUE TITLE
Peer to Peer Code review

### ISSUE THREAD

**Issue by benjp009** [RayhanTabase/to-do-list#18]
# 👋  @RayhanTabase 

### Great job so far !! 

Please try to arrange the code better to improve visibility : 

Well done adding the file jest.config.js 
`module.exports = {
  clearMocks: true,
  collectCoverage: true,
  coverageDirectory: 'coverage',
  coverageProvider: 'v8',
  restoreMocks: false,
  setupFiles: ['jest-localstorage-mock'],
};
`
Try to see if it works when adding it on package.json file as well

I would also have used folders for better visibility of the test files from the normal files to be tested.

**Comment by Debas-31** [comment]
# Good Job @RayhanTabase 
-  I guess it's better to use the jest describe method for each function.
